feat: Attach the user's name to the user message payload if known
jekalmin/extended_openai_conversation pull request #28
Opened 2023-11-17 08:05 UTC by Teagan42

# Motivation

I wanted my assistant to know who it was talking to.

# Approach

If there is a user_id attached to the context that is provided via `user_input`, retrieve the name of the user from HASS's authentication manager. This primarily applies when interacting with the UI or invoking the process service from a user context.

# Future Work

## Wake Words
Add voice recognition to wake word detection to differentiate the user who started the conversation

## Full Feature
Add voice recognition to differentiate the user who is currently speaking - allowing for multiple participate in a conversation

2023-11-17 14:56 UTC, jekalmin commented
Thank you for your work!
I just tried and seems to work well for me.

One concern I have is that since this is the first custom field(not required for openai) to put in the message, wonder if everyone want it to be added or not.

2023-11-18 01:03 UTC, Teagan42 commented
I was thinking about adding it to the core project as well

2023-11-18 15:54 UTC, jekalmin commented
If you don't mind, please let me keep this PR open for a while.
I am quite not sure whether this should be configurable or mandatory yet.

2023-11-20 03:49 UTC, Teagan42 commented
No problem

2023-11-20 04:07 UTC, Teagan42 commented
Went ahead and added it to the `config_flow` as you’re right, it should be optional for users.

2023-11-20 04:38 UTC, jekalmin commented
Thanks for going ahead!
I will try this today or tomorrow, and let you know if anything is needed.

2023-11-20 12:41 UTC, jekalmin requested changes
Could you add a label of new field in translations?
- [en.json](https://github.com/jekalmin/extended_openai_conversation/blob/13867d176c7740c9b55678b22c6cfb54fd4d9f1e/custom_components/extended_openai_conversation/translations/en.json)
- [ko.json](https://github.com/jekalmin/extended_openai_conversation/blob/13867d176c7740c9b55678b22c6cfb54fd4d9f1e/custom_components/extended_openai_conversation/translations/ko.json)
- [strings.json](https://github.com/jekalmin/extended_openai_conversation/blob/13867d176c7740c9b55678b22c6cfb54fd4d9f1e/custom_components/extended_openai_conversation/strings.json)

2023-11-22 16:42 UTC, Teagan42 commented on custom_components/extended_openai_conversation/config_flow.py
> +                "suggested_value": options[CONF_ATTACH_USERNAME]
Good catch

2023-11-23 12:25 UTC, jekalmin reviewed
Thanks for a change!
I left a quick comment below :D

2023-11-23 12:25 UTC, jekalmin commented on README.md
> +- `Attach Username`: Pass the active user's name (if applicaple) to OpenAI via rhe message payload. Currently, this only applies to conversations through the UI or REST API.
Just curious of what `rhe` stands for.

2023-12-05 06:05 UTC, Teagan42 commented on README.md
> +- `Attach Username`: Pass the active user's name (if applicaple) to OpenAI via rhe message payload. Currently, this only applies to conversations through the UI or REST API.
Typeo

2023-12-05 06:09 UTC, Teagan42 commented on README.md
> +- `Attach Username`: Pass the active user's name (if applicaple) to OpenAI via rhe message payload. Currently, this only applies to conversations through the UI or REST API.
Resolved

2023-12-06 01:57 UTC, jekalmin approved these changes
Thanks for your work!
I will apply this change in next release (currently released in [0.0.9-beta](https://github.com/jekalmin/extended_openai_conversation/releases/tag/0.0.9-beta1))

2023-12-06 01:59 UTC, merged